language: node_js
node_js:
- '8'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev
- npm install -g eslint
- npm install --save-dev eslint-plugin-jasmine -g
- npm install --save-dev babel-eslint -g
- npm install --save-dev eslint-plugin-inferno -g
- npm install -g codecov
script:
- npm run test -- --coverage && codecov
- npm run eslint
deploy:
  provider: heroku
  api_key:
    secure: rZMRLPoHUE46p4uqnHYE8Skh+D43RJrG88fbQD03GdRxuNCa50zBLR+PP99pHLhRdUkXfGiTaBkFHsu+up8pBQDcysY/RY4+B+V0pgTb+9qE8iHnmVvBADqhTzSUKjtoXvdGWIoaqBVsfnTQN9q9C2briPAToqJKjDybwn5GI7pmyWlWOv7X3rSyNF/ls9EbxrO1xLWNm94rPZVbbkxYvKlRvzsUZSNpexoRmQiVSxoos0sVV8/Aj6VZtlZzF3b99VoXD/l3FIrHO83F6izGf8Oh4vN8XbgV6g4mY0u639cSqtR3Osdd+ENppCKHaeKbNCfMjzIW2CHt3rvUSR2RkH9CLdESxt2t/jQDDcDazsM6+3FEw1vDAgvP/TAqt6oYtRDgfMcGr7eGYdQL1ZfLwU49R2dWp1x28z1O9O1bXKLaXgouBpcEpacfPfK4HBIz+3H/w2NYXK4z2WypUeHIfnTmD4rBz7cN8Nywz9sd1cbcTnDGkyU1UewIZLui3lbd8X6nHz7W0db/1S0FPlxvonr9TDr9juGsloh0Kfr9l1TO8rdskrbD+DupAKn2Ivip6GdvyOg38edoswB19t7xniiee1sGMd6GE/X81fo33EXGVaf7prqLTmD+Y9v9GL24zO/NbhbqIVe5kq+0d8HAwoOQljYdxM52EYOSxFoaDs8=
  app: inferno-todos
  on:
    branch: master
    repo: dydyFos/infernoTodos
    run:
    - npm build
    - rm .eslintrc.js
    - rm .gitignore
    - rm .snyk
    - rm .travis.yml
    - rm README.md
    - mv ./build/index.html .
    - mv ./build/static .
    - rm -rf ./public
    - rm -rf ./src
    - rm -rf ./fixtures
    - rm -rf ./build
    - rm -rf ./node_modules
    - rm -rf ./coverage
    - rm -rf ./git
after_success:
- git clone https://travis:$GITHUB_TOKEN@github.com/dydyFos/infernoTodos.git web
- cd web
- npm install
- npm run deploy
notifications:
  email: true
  slack:
    secure: JPRTw8dWWhIzoe8zv3/SjZE96oHRT6bqbaL5IyqJPeSbSta3ptj0KFx5Pk3NcNmA0fdQU6ExLPS65ZkN3Z1XgoloAh9FfRYsN6+Kn5FHS8+nDsBay7YRZJjrzqQ83U2YKpaIZq/aqIJtDg/6ht4FHtFG+LPkB6T68nSZtexjM51dYX9cIS4jucDjK/pdJ7W2HGHLpGFW/mZZ0qLodO6lS3bhj4xDOld+3fU5gR9svf/YaHGK5BU1r+YuqA2UHQjChLYNyqeZVF798yAkHQnE1Q6rgJn3yPMe61pDlDsuOp1sdiIlClDAZRX8GwCnC2m3Xc+DqQddOxSMqU0oZgxj+bgi004arNz60DrKx46U+CqS8LoPHn5x83xS4UbNRZS2GILHtovABTqUC11QwBLUIZPjO3xRfuWJSA5PdoGbSG9FCi+4NrFj/2kipNbQQFB7jrrz1/uyOQBPNGxJ9ssIS63tBceTkbfYqCqUp8agDRhnZw3KDVYAkkrKEJFMMDspxAab5BqogjmakCaIkzJpEPTKs/QbFx2FfRxydo/Vh2q5Uqkzz1ZAm1BLULyM8zSls0BG440wPrLNqBlEqjpX3r/H4RGT0+dcRMTunro9NknSmuT0p7lYiGeBB/lDmA9x4lPVzgBfB7Sv8xQTYt17PmVgiR5KWYn9zQxLcOc8jNQ=
