language: node_js
node_js:
  - '8'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - npm install -g eslint
  - npm install --save-dev eslint-plugin-jasmine -g
  - npm install --save-dev babel-eslint -g
  - npm install --save-dev eslint-plugin-inferno -g
  - npm install -g codecov
  # - npm install -g snyk
# before_script:
#   - snyk auth $SNYK_TOKEN
#   - snyk test
script:
  - npm run test -- --coverage && codecov
  - npm run eslint
# after_script:
#   - snyk test
deploy:
  provider: heroku
  api_key:
    secure: rZMRLPoHUE46p4uqnHYE8Skh+D43RJrG88fbQD03GdRxuNCa50zBLR+PP99pHLhRdUkXfGiTaBkFHsu+up8pBQDcysY/RY4+B+V0pgTb+9qE8iHnmVvBADqhTzSUKjtoXvdGWIoaqBVsfnTQN9q9C2briPAToqJKjDybwn5GI7pmyWlWOv7X3rSyNF/ls9EbxrO1xLWNm94rPZVbbkxYvKlRvzsUZSNpexoRmQiVSxoos0sVV8/Aj6VZtlZzF3b99VoXD/l3FIrHO83F6izGf8Oh4vN8XbgV6g4mY0u639cSqtR3Osdd+ENppCKHaeKbNCfMjzIW2CHt3rvUSR2RkH9CLdESxt2t/jQDDcDazsM6+3FEw1vDAgvP/TAqt6oYtRDgfMcGr7eGYdQL1ZfLwU49R2dWp1x28z1O9O1bXKLaXgouBpcEpacfPfK4HBIz+3H/w2NYXK4z2WypUeHIfnTmD4rBz7cN8Nywz9sd1cbcTnDGkyU1UewIZLui3lbd8X6nHz7W0db/1S0FPlxvonr9TDr9juGsloh0Kfr9l1TO8rdskrbD+DupAKn2Ivip6GdvyOg38edoswB19t7xniiee1sGMd6GE/X81fo33EXGVaf7prqLTmD+Y9v9GL24zO/NbhbqIVe5kq+0d8HAwoOQljYdxM52EYOSxFoaDs8=
  app: inferno-todos
  on:
    branch: master
    repo: dydyFos/infernoTodos
    run:
      - "npm build"
      - "rm .eslintrc.js"
      - "rm .gitignore"
      - "rm .snyk"
      - "rm .travis.yml"
      - "rm README.md"
      - "mv ./build/index.html ."
      - "mv ./build/static ."
      - "rm -rf ./public"
      - "rm -rf ./src"
      - "rm -rf ./fixtures"
      - "rm -rf ./build"
      - "rm -rf ./node_modules"
      - "rm -rf ./coverage"
      - "rm -rf ./git"
after_success:
  - "git clone https://github.com/dydyFos/infernoTodos.git web -c username='travis' -c password='$GITHUB_TOKEN'"
  - "cd web"
  - "npm run deploy"
# env:
#   snyk:
#     secure: DO8MuoJkCX03QNX92uB3/kllCncVWJDyk9gRauzt8r2hydSIwHhcchahJwOs9JBVh0Ha4V2yT8UnIc6+BXTqlMP0EAdIYQq9uq7arQ7US1h3DnNntOMLUSH2cshtMgEMumWZzJYR242fLvrJfU2F8zCVaeW5W0QcibdWs8LL1bmWlZxEVy4VfyvNJbV1twH3SZWJ0+J2SRh0g7fPg+A8VcClJ79oAYmB5WAVqPAM3XZQC4Cy/XL25Y8fkTJtAcVHVeB6uSpko9uqLfUC9lJmqSneJG8pRhJoxV79JI/REBCj3zx/e5dK5LncM0cFZUdfr/b1sZ6sneI1+91m0P66Ek6ebgLuCt51TbYK6mp2AJa3AUXYZtpj0HI/CT26F+R111rZjrQVQzyzR5j5aoAQXawS8oBeBA6Tb18POYTAtt0TvayH2Jv8Zk6hh2pYXRku77NbNxr7BSmBi22eWCkDBPg+E5CVTLSS/DMCz+DLb+hjtrPupjSOBX1AJnNVTitFAccStC+y5SaXzBCKlFI2kSod5vCBkTXPQX671dfq2UROSmXh8AsPLHoEEUlUebBzl6bSEEAv5a2OprB2TaL0Nt7EnkOzdqU0D+3eviqtwT/OEVS8M/HZfBUp/TOdZuabzCp/9sLQnwW7hwLLZQImpxPX7IGPTB0Vt6MqzQ6yuPU=
